# SPDX-FileCopyrightText: 2026 Gundu Labs
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "pam-gaze-grosshack"
version = "0.2.12"
edition = "2024"
description = "Deprecated compatibility shim for Gaze simultaneous PAM module"
categories.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
publish.workspace = true
readme.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
pam-gaze = { path = "../pam-gaze", features = ["shim-dep"] }
libc = "0.2.189"
