# SPDX-FileCopyrightText: 2026 Gundu Labs
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "pam-gaze-grosshack"
version = "0.2.12"
edition = "2024"
description = "Simultaneous face and password authentication PAM module for Gaze"
categories.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
publish.workspace = true
readme.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
pam-gaze-core = { path = "../pam-gaze-core" }
libc = "0.2.189"
tokio = { version = "1.53.1", features = ["full"] }
