[package]
name = "gaze_gui"
version.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "gaze-gui"
path = "src/main.rs"

[dependencies]
gaze_common = { path = "../gaze_common" }
gtk4 = { version = "0.9.7", features = ["gnome_46"] }
libadwaita = { version = "0.7.2", features = ["v1_4"] }
zbus = "4.4.0"
anyhow = "1.0.102"
opencv = "0.98.1"
